# Generated by Django 4.2 on 2023-04-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='Cost',
        ),
        migrations.RemoveField(
            model_name='student',
            name='document',
        ),
        migrations.AddField(
            model_name='student',
            name='Details',
            field=models.CharField(default='', max_length=20, verbose_name='Details'),
            preserve_default=False,
        ),
    ]
